<?php
/**
 * File: admin_manajemen_kelas.php
  * Versi dengan Sidebar
   */

   require_once 'config/koneksi.php';

   // Keamanan
   if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'admin') {
       header("Location: logout.php");
           exit();
           }

           $pesan = '';
           if (isset($_GET['status']) && $_GET['status'] == 'sukses_hapus') {
               $pesan = "<div class='alert alert-success'>Kelas berhasil dihapus oleh Admin.</div>";
               }

               // Ambil semua data kelas
               $query = "
                   SELECT k.id, k.nama_kelas, k.mata_pelajaran, u.nama_lengkap AS nama_guru,
                              (SELECT COUNT(*) FROM pendaftaran_kelas WHERE id_kelas = k.id) AS jumlah_siswa
                                  FROM kelas k JOIN pengguna u ON k.id_guru = u.id
                                      ORDER BY u.nama_lengkap, k.nama_kelas
                                      ";
                                      $result_kelas = $koneksi->query($query);

                                      include_once 'templates/header_admin.php'; // Panggil header admin baru
                                      ?>

                                      <h1 class="mb-4">Manajemen Kelas</h1>
                                      <?php if(!empty($pesan)) echo $pesan; ?>

                                      <div class="card">
                                          <div class="card-body">
                                                  <div class="table-responsive">
                                                              <table class="table table-striped table-hover">
                                                                              <thead>
                                                                                                  <tr>
                                                                                                                          <th>Nama Kelas</th>
                                                                                                                                                  <th>Mata Pelajaran</th>
                                                                                                                                                                          <th>Guru Pengampu</th>
                                                                                                                                                                                                  <th>Jumlah Siswa</th>
                                                                                                                                                                                                                          <th>Aksi</th>
                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                              </thead>
                                                                                                                                                                                                                                                                              <tbody>
                                                                                                                                                                                                                                                                                                  <?php while($kelas = $result_kelas->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                              <td><?php echo htmlspecialchars($kelas['nama_kelas']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                      <td><?php echo htmlspecialchars($kelas['mata_pelajaran']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                              <td><?php echo htmlspecialchars($kelas['nama_guru']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                      <td><?php echo $kelas['jumlah_siswa']; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="admin_hapus_kelas.php?id=<?php echo $kelas['id']; ?>" class="btn btn-danger btn-sm" onclick="return confirm('PERINGATAN: Anda sebagai Admin akan menghapus kelas ini secara permanen. Lanjutkan?')">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Hapus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              include_once 'templates/footer.php'; // Panggil footer biasa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ?>