<?php
/**
 * File: admin_laporan.php
  * Halaman untuk Admin melihat statistik keseluruhan LMS.
   */

   require_once 'config/koneksi.php';

   // Keamanan: Pastikan hanya ADMIN yang bisa akses
   if (!isset($_SESSION['user_id']) || $_SESSION['peran'] != 'admin') {
       header("Location: logout.php");
           exit();
           }

           // === LOGIKA UNTUK MENGAMBIL DATA STATISTIK ===

           // Menghitung Total Guru
           $result_guru = $koneksi->query("SELECT COUNT(id) as total FROM pengguna WHERE peran = 'guru'");
           $total_guru = $result_guru->fetch_assoc()['total'];

           // Menghitung Total Siswa
           $result_siswa = $koneksi->query("SELECT COUNT(id) as total FROM pengguna WHERE peran = 'siswa'");
           $total_siswa = $result_siswa->fetch_assoc()['total'];

           // Menghitung Total Pengguna (Guru + Siswa + 1 Admin)
           $total_pengguna = $total_guru + $total_siswa + 1;

           // Menghitung Total Kelas
           $result_kelas = $koneksi->query("SELECT COUNT(id) as total FROM kelas");
           $total_kelas = $result_kelas->fetch_assoc()['total'];

           // Menghitung Total Materi
           $result_materi = $koneksi->query("SELECT COUNT(id) as total FROM materi");
           $total_materi = $result_materi->fetch_assoc()['total'];

           // Menghitung Total Kuis
           $result_kuis = $koneksi->query("SELECT COUNT(id) as total FROM soal");
           $total_kuis = $result_kuis->fetch_assoc()['total'];


           include_once 'templates/header_admin.php'; // Panggil header admin
           ?>

           <h1 class="mb-4">Laporan & Statistik</h1>
           <p class="lead">Gambaran umum aktivitas dan data di dalam platform CAKAP DIGITAL INDONESIA.</p>
           <hr class="mb-4">

           <div class="row g-4">
               <div class="col-md-4">
                       <div class="card text-center h-100 shadow-sm">
                                   <div class="card-body">
                                                   <i class="bi bi-people-fill display-3 text-primary"></i>
                                                                   <h1 class="card-title fw-bold mt-2"><?php echo $total_pengguna; ?></h1>
                                                                                   <p class="card-text text-muted">Total Pengguna</p>
                                                                                               </div>
                                                                                                       </div>
                                                                                                           </div>

                                                                                                               <div class="col-md-4">
                                                                                                                       <div class="card text-center h-100 shadow-sm">
                                                                                                                                   <div class="card-body">
                                                                                                                                                   <i class="bi bi-person-video3 display-3 text-success"></i>
                                                                                                                                                                   <h1 class="card-title fw-bold mt-2"><?php echo $total_guru; ?></h1>
                                                                                                                                                                                   <p class="card-text text-muted">Total Guru</p>
                                                                                                                                                                                               </div>
                                                                                                                                                                                                       </div>
                                                                                                                                                                                                           </div>

                                                                                                                                                                                                               <div class="col-md-4">
                                                                                                                                                                                                                       <div class="card text-center h-100 shadow-sm">
                                                                                                                                                                                                                                   <div class="card-body">
                                                                                                                                                                                                                                                   <i class="bi bi-person-fill display-3 text-info"></i>
                                                                                                                                                                                                                                                                   <h1 class="card-title fw-bold mt-2"><?php echo $total_siswa; ?></h1>
                                                                                                                                                                                                                                                                                   <p class="card-text text-muted">Total Siswa</p>
                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                               <div class="col-md-4">
                                                                                                                                                                                                                                                                                                                       <div class="card text-center h-100 shadow-sm">
                                                                                                                                                                                                                                                                                                                                   <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                   <i class="bi bi-collection-fill display-3 text-warning"></i>
                                                                                                                                                                                                                                                                                                                                                                   <h1 class="card-title fw-bold mt-2"><?php echo $total_kelas; ?></h1>
                                                                                                                                                                                                                                                                                                                                                                                   <p class="card-text text-muted">Total Kelas</p>
                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                                                                                                                               <div class="col-md-4">
                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="card text-center h-100 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                   <i class="bi bi-book-half display-3 text-danger"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <h1 class="card-title fw-bold mt-2"><?php echo $total_materi; ?></h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p class="card-text text-muted">Total Materi</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="col-md-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="card text-center h-100 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <i class="bi bi-patch-question-fill display-3 text-secondary"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <h1 class="card-title fw-bold mt-2"><?php echo $total_kuis; ?></h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p class="card-text text-muted">Total Kuis</big>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           include_once 'templates/footer_admin.php'; // Panggil footer admin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ?>